import io
import os
import re
import html
from typing import Optional, List
from core.models import SubmissionRecord, EvaluationResult

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


class ReportExporter:
    """Generates formatted Text, HTML Print, and PDF evaluation reports for student submissions."""

    @staticmethod
    def generate_text_report(submission: SubmissionRecord) -> str:
        """Builds a comprehensive, readable plain-text report."""
        details: Optional[EvaluationResult] = submission.evaluation_details
        model_name = submission.model_used or (details.model_used if details else "Gemini AI")
        
        lines = []
        lines.append("=" * 80)
        lines.append(f"{'AGENTIC ML SPECIFICATION GRADING REPORT':^80}")
        lines.append("=" * 80)
        lines.append(f"Student Name   : {submission.student_name}")
        lines.append(f"Project Path   : {submission.folder_name}")
        lines.append(f"Submission ID  : {submission.id}")
        lines.append(f"Timestamp (UTC): {submission.timestamp}")
        lines.append(f"AI Model Used  : {model_name}")
        lines.append(f"Overall Score  : {submission.score:.1f}% ({submission.letter_grade})")
        if details:
            lines.append(f"Total Points   : {details.total_score:.1f} / {details.max_possible_score:.1f} pts")
        lines.append("-" * 80)

        if details:
            lines.append(f"\nOVERALL SUMMARY:\n{details.summary}\n")

            if details.strengths:
                lines.append("KEY STRENGTHS:")
                for s in details.strengths:
                    lines.append(f"  ✓ {s}")
                lines.append("")

            if details.deductions:
                lines.append("DEDUCTIONS & AREAS FOR IMPROVEMENT:")
                for d in details.deductions:
                    lines.append(f"  ⚠ {d}")
                lines.append("")

            lines.append("=" * 80)
            lines.append("DETAILED SPECIFICATION CRITERIA BREAKDOWN:")
            lines.append("=" * 80)
            
            for c in details.criteria:
                status_symbol = "[✓ PASS]" if c.status == "PASS" else ("[⚠ PARTIAL]" if c.status == "PARTIAL" else "[✗ FAIL]")
                lines.append(f"\n{status_symbol} {c.title} ({c.earned_score:.1f}/{c.max_score:.1f} pts)")
                lines.append(f"  Category   : {c.category}")
                lines.append(f"  Description: {c.description}")
                lines.append(f"  Findings   : {c.feedback}")
                if c.evidence:
                    lines.append(f"  Evidence   : {c.evidence}")
                if c.earned_score < c.max_score:
                    if c.deduction_reason:
                        lines.append(f"  ⚠️ Deduction: {c.deduction_reason}")
                    if c.fix_recommendation:
                        lines.append(f"  💡 How to Fix: {c.fix_recommendation}")
                lines.append("-" * 40)

        lines.append("\n" + "=" * 80)
        lines.append("End of Evaluation Report - Generated by AutoGrader Pro")
        lines.append("=" * 80 + "\n")
        return "\n".join(lines)

    @staticmethod
    def generate_html_report(submission: SubmissionRecord) -> str:
        """Builds a responsive, high-contrast HTML report optimized for browser viewing and printing to PDF."""
        details = submission.evaluation_details
        model_name = html.escape(submission.model_used or (details.model_used if details else "Gemini AI"))
        student_name = html.escape(submission.student_name)
        folder_name = html.escape(submission.folder_name)
        summary = html.escape(details.summary if details else "Evaluation complete.")
        
        score_color = "#16a34a" if submission.score >= 85 else ("#d97706" if submission.score >= 70 else "#dc2626")

        strengths_html = ""
        if details and details.strengths:
            strengths_html = "".join([f"<li style='margin-bottom: 6px;'>✓ {html.escape(s)}</li>" for s in details.strengths])
        else:
            strengths_html = "<li>No significant strengths noted.</li>"

        deductions_html = ""
        if details and details.deductions:
            deductions_html = "".join([f"<li style='margin-bottom: 6px;'>⚠ {html.escape(d)}</li>" for d in details.deductions])
        else:
            deductions_html = "<li>✓ Zero deductions! Perfect specification match.</li>"

        criteria_rows = ""
        if details and details.criteria:
            for c in details.criteria:
                status_color = "#16a34a" if c.status == "PASS" else ("#d97706" if c.status == "PARTIAL" else "#dc2626")
                is_perf = c.earned_score >= c.max_score
                
                deduction_block = ""
                if not is_perf and c.deduction_reason:
                    deduction_block = f"<div style='margin-top: 6px; color: #b91c1c; font-size: 0.85rem;'><strong>⚠️ Deduction:</strong> {html.escape(c.deduction_reason)}</div>"
                
                fix_block = ""
                if not is_perf and c.fix_recommendation:
                    fix_block = f"<div style='margin-top: 4px; color: #1d4ed8; font-size: 0.85rem;'><strong>💡 How to Fix:</strong> {html.escape(c.fix_recommendation)}</div>"

                evidence_block = ""
                if c.evidence:
                    evidence_block = f"<div style='margin-top: 4px; color: #64748b; font-size: 0.85rem;'><strong>Evidence:</strong> {html.escape(c.evidence)}</div>"

                criteria_rows += f"""
                <tr style='border-bottom: 1px solid #e2e8f0;'>
                    <td style='padding: 10px; vertical-align: top;'>
                        <strong>{html.escape(c.title)}</strong><br/>
                        <span style='color: #64748b; font-size: 0.8rem;'>{html.escape(c.category)}</span>
                    </td>
                    <td style='padding: 10px; vertical-align: top; text-align: center; font-weight: bold;'>
                        {c.earned_score:.1f} / {c.max_score:.1f}
                    </td>
                    <td style='padding: 10px; vertical-align: top; text-align: center;'>
                        <span style='color: {status_color}; font-weight: bold;'>{html.escape(c.status)}</span>
                    </td>
                    <td style='padding: 10px; vertical-align: top;'>
                        <div>{html.escape(c.feedback)}</div>
                        {evidence_block}
                        {deduction_block}
                        {fix_block}
                    </td>
                </tr>
                """

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{student_name} - Grade Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background: #f8fafc; color: #1e293b; margin: 0; padding: 24px; }}
        .report-container {{ max-width: 860px; margin: 0 auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 32px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }}
        .header {{ display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #6366f1; padding-bottom: 16px; margin-bottom: 20px; }}
        .title h1 {{ margin: 0 0 4px 0; font-size: 24px; color: #0f172a; }}
        .title p {{ margin: 0; color: #64748b; font-size: 14px; }}
        .score-pill {{ text-align: right; background: #f1f5f9; padding: 12px 20px; border-radius: 8px; border: 1px solid #cbd5e1; }}
        .score-num {{ font-size: 28px; font-weight: 800; color: {score_color}; }}
        .meta-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; background: #f8fafc; padding: 14px; border-radius: 6px; border: 1px solid #e2e8f0; margin-bottom: 24px; font-size: 14px; }}
        .feedback-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }}
        .fb-card {{ padding: 16px; border-radius: 6px; border: 1px solid #e2e8f0; font-size: 14px; }}
        .fb-card.strengths {{ background: #f0fdf4; border-color: #bbf7d0; }}
        .fb-card.deductions {{ background: #fef2f2; border-color: #fecaca; }}
        .fb-card h3 {{ margin-top: 0; font-size: 15px; margin-bottom: 8px; }}
        .fb-card ul {{ margin: 0; padding-left: 18px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13.5px; }}
        th {{ background: #f1f5f9; padding: 10px; text-align: left; border-bottom: 2px solid #cbd5e1; }}
        .no-print {{ margin-bottom: 16px; text-align: right; }}
        .btn-print {{ background: #4f46e5; color: #fff; border: none; padding: 10px 18px; border-radius: 6px; font-weight: 600; cursor: pointer; }}
        @media print {{
            body {{ background: #fff; padding: 0; }}
            .report-container {{ border: none; box-shadow: none; padding: 0; }}
            .no-print {{ display: none; }}
        }}
    </style>
</head>
<body>
    <div class="report-container">
        <div class="no-print">
            <button class="btn-print" onclick="window.print()">🖨️ Print / Save to PDF</button>
        </div>
        <div class="header">
            <div class="title">
                <h1>AutoGrader Pro - Grade Report</h1>
                <p>AI Specification Compliance Evaluation powered by <strong>{model_name}</strong></p>
            </div>
            <div class="score-pill">
                <div class="score-num">{submission.score:.1f}%</div>
                <div style="font-weight: 700; color: #475569;">Grade: {html.escape(submission.letter_grade)}</div>
            </div>
        </div>

        <div class="meta-grid">
            <div><strong>Student:</strong> {student_name}</div>
            <div><strong>AI Model Used:</strong> {model_name}</div>
            <div><strong>Project Folder:</strong> <code>{folder_name}</code></div>
            <div><strong>Evaluated:</strong> {html.escape(submission.timestamp[:19].replace('T', ' '))} UTC</div>
        </div>

        <div style="margin-bottom: 20px;">
            <h3 style="margin: 0 0 6px 0; font-size: 16px;">Overall Summary</h3>
            <p style="margin: 0; color: #334155; line-height: 1.5; font-size: 14px;">{summary}</p>
        </div>

        <div class="feedback-grid">
            <div class="fb-card strengths">
                <h3 style="color: #166534;">✓ Key Strengths</h3>
                <ul>{strengths_html}</ul>
            </div>
            <div class="fb-card deductions">
                <h3 style="color: #991b1b;">⚠ Deductions & Gaps</h3>
                <ul>{deductions_html}</ul>
            </div>
        </div>

        <h3 style="margin: 24px 0 8px 0; font-size: 16px;">Specification Criteria Breakdown</h3>
        <table>
            <thead>
                <tr>
                    <th style="width: 25%;">Criterion</th>
                    <th style="width: 12%; text-align: center;">Score</th>
                    <th style="width: 12%; text-align: center;">Status</th>
                    <th style="width: 51%;">Findings & Remediation</th>
                </tr>
            </thead>
            <tbody>
                {criteria_rows}
            </tbody>
        </table>
        
        <div style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center;">
            AutoGrader Pro &bull; Submission ID: {html.escape(submission.id)}
        </div>
    </div>
</body>
</html>
"""

    @classmethod
    def generate_pdf_report(cls, submission: SubmissionRecord) -> bytes:
        """Builds a styled PDF document. Uses ReportLab when available, with a resilient native PDF fallback."""
        if REPORTLAB_AVAILABLE:
            try:
                return cls._generate_reportlab_pdf(submission)
            except Exception as e:
                print(f"Warning: ReportLab PDF rendering exception ({e}), falling back to built-in PDF writer.")
                return cls._generate_native_pdf(submission)
        else:
            return cls._generate_native_pdf(submission)

    @classmethod
    def _generate_reportlab_pdf(cls, submission: SubmissionRecord) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )

        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#0f172a'),
            fontName='Helvetica-Bold',
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            'DocSub',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#64748b'),
            spaceAfter=15
        )
        section_heading = ParagraphStyle(
            'SecHead',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#1e293b'),
            fontName='Helvetica-Bold',
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontSize=9.5,
            leading=13,
            textColor=colors.HexColor('#334155')
        )
        body_bold = ParagraphStyle(
            'BodyBold',
            parent=body_style,
            fontName='Helvetica-Bold'
        )
        deduction_style = ParagraphStyle(
            'DeductionStyle',
            parent=styles['Normal'],
            fontSize=9,
            leading=12,
            textColor=colors.HexColor('#b91c1c')
        )
        fix_style = ParagraphStyle(
            'FixStyle',
            parent=styles['Normal'],
            fontSize=9,
            leading=12,
            textColor=colors.HexColor('#1d4ed8')
        )

        elements = []

        # 1. Header & Title
        elements.append(Paragraph("AutoGrader Pro - Submission Evaluation Report", title_style))
        details = submission.evaluation_details
        model_name = submission.model_used or (details.model_used if details else "Gemini AI")
        elements.append(Paragraph(f"Automated specification grading powered by <b>{model_name}</b>", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#6366f1'), spaceAfter=15))

        # 2. Metadata Box / Score Card Table
        score_color = colors.HexColor('#16a34a') if submission.score >= 85 else (colors.HexColor('#d97706') if submission.score >= 70 else colors.HexColor('#dc2626'))
        
        meta_data = [
            [
                Paragraph("<b>Student:</b>", body_style),
                Paragraph(submission.student_name, body_bold),
                Paragraph("<b>Overall Score:</b>", body_style),
                Paragraph(f"<font color='{score_color}' size=14><b>{submission.score:.1f}% ({submission.letter_grade})</b></font>", body_style)
            ],
            [
                Paragraph("<b>Project Folder:</b>", body_style),
                Paragraph(f"<font size=8>{submission.folder_name}</font>", body_style),
                Paragraph("<b>Model Used:</b>", body_style),
                Paragraph(f"<b>{model_name}</b>", body_style)
            ],
            [
                Paragraph("<b>Submission Date:</b>", body_style),
                Paragraph(submission.timestamp[:19].replace('T', ' ') + " UTC", body_style),
                Paragraph("<b>Points Total:</b>", body_style),
                Paragraph(f"{details.total_score:.1f} / {details.max_possible_score:.1f} pts" if details else "--", body_style)
            ]
        ]
        meta_table = Table(meta_data, colWidths=[90, 210, 80, 150])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 15))

        # 3. Overall Summary
        if details and details.summary:
            elements.append(Paragraph("Executive Summary", section_heading))
            elements.append(Paragraph(details.summary, body_style))
            elements.append(Spacer(1, 10))

        # 4. Strengths and Deductions
        if details:
            if details.strengths or details.deductions:
                strengths_p = [Paragraph(f"✓ {s}", body_style) for s in details.strengths] or [Paragraph("None noted", body_style)]
                deductions_p = [Paragraph(f"⚠ {d}", body_style) for d in details.deductions] or [Paragraph("Zero deductions!", body_style)]
                
                max_len = max(len(strengths_p), len(deductions_p))
                summary_rows = [
                    [Paragraph("<b>Key Strengths</b>", body_style), Paragraph("<b>Deductions & Gaps</b>", body_style)]
                ]
                for i in range(max_len):
                    col1 = strengths_p[i] if i < len(strengths_p) else Paragraph("", body_style)
                    col2 = deductions_p[i] if i < len(deductions_p) else Paragraph("", body_style)
                    summary_rows.append([col1, col2])

                summary_table = Table(summary_rows, colWidths=[265, 265])
                summary_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (0, 0), colors.HexColor('#f0fdf4')),
                    ('BACKGROUND', (1, 0), (1, 0), colors.HexColor('#fef2f2')),
                    ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('TOPPADDING', (0, 0), (-1, -1), 4),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ]))
                elements.append(summary_table)
                elements.append(Spacer(1, 15))

            # 5. Criteria Breakdown
            elements.append(Paragraph("Detailed Specification Criteria Breakdown", section_heading))
            
            crit_table_data = [
                [
                    Paragraph("<b>Criterion / Dimension</b>", body_style),
                    Paragraph("<b>Score</b>", body_style),
                    Paragraph("<b>Status</b>", body_style),
                    Paragraph("<b>Findings, Evidence & Remediation</b>", body_style)
                ]
            ]

            for c in details.criteria:
                is_perf = c.earned_score >= c.max_score
                status_color = "#16a34a" if c.status == "PASS" else ("#d97706" if c.status == "PARTIAL" else "#dc2626")
                
                cell_findings = [
                    Paragraph(f"<b>Findings:</b> {c.feedback}", body_style)
                ]
                if c.evidence:
                    cell_findings.append(Paragraph(f"<b>Evidence:</b> <font color='#475569'>{c.evidence}</font>", body_style))
                if not is_perf and c.deduction_reason:
                    cell_findings.append(Paragraph(f"<b>⚠️ Deduction:</b> {c.deduction_reason}", deduction_style))
                if not is_perf and c.fix_recommendation:
                    cell_findings.append(Paragraph(f"<b>💡 How to Fix:</b> {c.fix_recommendation}", fix_style))

                crit_table_data.append([
                    Paragraph(f"<b>{c.title}</b><br/><font color='#64748b' size=7.5>{c.category}</font>", body_style),
                    Paragraph(f"<b>{c.earned_score:.1f}</b>/{c.max_score:.1f}", body_style),
                    Paragraph(f"<font color='{status_color}'><b>{c.status}</b></font>", body_style),
                    cell_findings
                ])

            crit_table = Table(crit_table_data, colWidths=[130, 45, 55, 300])
            crit_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1')),
                ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ]))
            elements.append(crit_table)

        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()

    @classmethod
    def _generate_native_pdf(cls, submission: SubmissionRecord) -> bytes:
        """Pure-Python standard PDF generator fallback requiring zero external libraries."""
        text_content = cls.generate_text_report(submission)
        
        raw_lines = text_content.splitlines()
        page_lines = []
        lines_per_page = 55
        
        for i in range(0, len(raw_lines), lines_per_page):
            chunk = raw_lines[i:i + lines_per_page]
            page_lines.append(chunk)

        objects: List[bytes] = []
        page_obj_ids = []

        objects.append(b"<< /Type /Outlines /Count 0 >>")
        
        for idx, plines in enumerate(page_lines):
            stream_parts = [
                b"BT",
                b"/F1 9 Tf",
                b"12 TL",
                b"40 750 Td"
            ]
            for l in plines:
                clean_line = l.replace('\\', '\\\\').replace('(', '\\(').replace(')', '\\)')
                stream_parts.append(f"({clean_line}) Tj".encode('latin-1', 'replace'))
                stream_parts.append(b"T*")
            stream_parts.append(b"ET")
            stream_data = b"\n".join(stream_parts)
            
            content_obj = f"<< /Length {len(stream_data)} >>\nstream\n".encode('ascii') + stream_data + b"\nendstream"
            objects.append(content_obj)
            content_id = len(objects)

            page_obj = (
                f"<< /Type /Page /Parent 3 0 R /MediaBox [0 0 612 792] "
                f"/Contents {content_id} 0 R /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Courier >> >> >> >>"
            ).encode('ascii')
            objects.append(page_obj)
            page_obj_ids.append(len(objects))

        kids_str = " ".join([f"{pid} 0 R" for pid in page_obj_ids])
        pages_root = f"<< /Type /Pages /Kids [{kids_str}] /Count {len(page_obj_ids)} >>".encode('ascii')
        catalog_obj = b"<< /Type /Catalog /Pages 3 0 R >>"

        all_objs = [catalog_obj, objects[0], pages_root] + objects[1:]
        
        out = io.BytesIO()
        out.write(b"%PDF-1.4\n")
        offsets = [0]
        for i, obj in enumerate(all_objs, 1):
            offsets.append(out.tell())
            out.write(f"{i} 0 obj\n".encode('ascii'))
            out.write(obj)
            out.write(b"\nendobj\n")
        
        xref_pos = out.tell()
        out.write(b"xref\n")
        out.write(f"0 {len(all_objs) + 1}\n".encode('ascii'))
        out.write(b"0000000000 65535 f \n")
        for off in offsets[1:]:
            out.write(f"{off:010d} 00000 n \n".encode('ascii'))
        
        out.write(b"trailer\n")
        out.write(f"<< /Size {len(all_objs) + 1} /Root 1 0 R >>\n".encode('ascii'))
        out.write(b"startxref\n")
        out.write(f"{xref_pos}\n%%EOF\n".encode('ascii'))

        return out.getvalue()
